---
title: "data_wrangling"
author: "Nikki Shintaku"
date: "4/16/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
library(tidyverse)
library(ggthemes)
library(lubridate)

USGS_gage_height <- read.csv("./Data/Raw/USGS_tahoe_gage_height.csv")
NOAA_climate <- read.csv("./Data/Raw/NOAA_Tahoe_climate_data.csv")

#theme
mytheme <- theme_stata(base_size = 14, base_family = "sans", scheme = "s2mono") +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")

theme_set(mytheme)
```

```{r}
USGS_gage_height$datetime <- as.Date(USGS_gage_height$datetime, format = "%m/%d/%y") 
USGS_gage_height$datetime <- format(USGS_gage_height$datetime, "%y%m%d")

#paste 19 if the input is greater than 181231 or 20 if it is less than 
create.early.dates <- (function(d) {
       paste0(ifelse(d > 191231,"19","20"),d)
       })
USGS_gage_height$datetime <- create.early.dates(USGS_gage_height$datetime)
USGS_gage_height$datetime <- as.Date(USGS_gage_height$datetime, format = "%Y%m%d")
class(USGS_gage_height$datetime)
```

```{r}
#changing date on NOAA Data
class(NOAA_climate$DATE)
NOAA_climate$DATE <- as.Date(NOAA_climate$DATE, format = "%Y-%m-%d")
class(NOAA_climate$DATE)
```

```{r}
#Wrangling USGS data, keeping only datetime, qual code, and gage_height
USGS_date_gage <- select(USGS_gage_height, datetime, gage_height, qual_code)

names(USGS_date_gage)[1] <- "DATE"

write.csv(USGS_date_gage, file = "./Data/Processed/USGS_Site10337000_gage_processed.csv", row.names = FALSE)
```

```{r}
#Wrangling NOAA data
#TAHOE CITY, CA US
NOAA_Tahoecity_climate <- 
  NOAA_climate %>%
  filter(NAME == "TAHOE CITY, CA US") %>%
  select(NAME, DATE:TMIN)

interval(first(NOAA_Tahoecity_climate$DATE), last(NOAA_Tahoecity_climate$DATE))
#1903-09-13 UTC--2020-03-30 UTC

write.csv(NOAA_Tahoecity_climate, file = "./Data/Processed/NOAA_TahoeCity_climate_processed.csv", row.names = FALSE)
```

```{r}
#combining datasets into one
USGS_NOAA_combined <- full_join(USGS_date_gage, NOAA_Tahoecity_climate)

USGS_NOAA_combined <- arrange(USGS_NOAA_combined, DATE)

interval(first(USGS_NOAA_combined$DATE), last(USGS_NOAA_combined$DATE))
class(USGS_NOAA_combined$DATE)

write.csv(USGS_NOAA_combined, file = "./Data/Processed/USGS_NOAA_combined_processed.csv", row.names = FALSE)
```


